---

  - name: Install packages
    apt: name=apt-transport-https update_cache=yes 

  - name: Add key
    shell: curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -

  - name: Add source list for kubernetes
    shell: |
       cat <<EOF >/etc/apt/sources.list.d/kubernetes.list
       > deb http://apt.kubernetes.io/ kubernetes-xenial main
       > EOF

  - name: Update apt cache
    apt: update_cache=yes

  - name: Install kubelet, kubeadm and kubectl
    apt: name={{item}} state=latest
    with_items:
        - kubelet
        - kubeadm
        - kubectl

  - name: Disable swap
    shell: swapoff -a
 
  - shell: sysctl net.bridge.bridge-nf-call-iptables=1

  - name: Initialize using kubeadm
    shell: kubeadm init --token-ttl 0 | grep 'kubeadm join --token'
    register: kubeadm_join_cmd

  - name: Store kubeadm join command in $HOME/kube_join_cmd file
    shell: touch $HOME/kube_join_cmd ; {{kubeadm_join_cmd.stdout}} >> $HOME/kube_join_cmd

  - name: Configuration
    shell: | 
       mkdir -p $HOME/.kube
       cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
       chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Run the kubeadm join command with token
    shell: {{kubeadm_join_cmd.stdout}}

  - shell: |
       kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
       kubectl get pods --all-namespaces
 
